version: 2

project_name: sbb-tui

before:
  hooks:
    - go mod tidy

builds:
  - binary: sbb-tui
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Tag}}
    goos:
      - linux
      - darwin
      - windows

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: sbb-tui
    commit_author:
      name: Necrom4
      email: diogofpombeiro@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    description: "Swiss SBB/CFF/FFS timetable app for the terminal"
    license: "MIT"
    install: |
      bin.install "sbb-tui"
    repository:
      owner: Necrom4
      name: homebrew-tap
      branch: master
      token: "{{ .Env.GH_TOKEN }}"
