[tools]
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
pre-commit = "latest"
"go:golang.org/x/tools/cmd/godoc" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
yq = "latest"

[env]
# Styles
_S_RESET = "\u001b[0m"
_S_BOLD = "\u001b[1m"
_S_URL = "\u001b[4m"

# Colors
_C_RED = "\u001b[31m"
_C_GREEN = "\u001b[32m"
_C_MAGENTA = "\u001b[35m"
_C_BLUE = "\u001b[34m"

# Hyperlink Parts
_LINK_START = "\u001b]8;;"
_LINK_SEP = "\u001b\\"
_LINK_END = "\u001b]8;;\u001b\\"

[tasks.init]
description = "Install hooks and setup environment"
run = "pre-commit install"

[tasks.pre-commit-run]
description = "Run a pre-commit hook by id"
quiet = true
usage = """
arg "[hook-id]" help="pre-commit hook id to run"
complete "hook-id" run="yq eval '.repos[0].hooks[].id' .pre-commit-config.yaml"
flag "-a --all-files" help="Run on all files"
flag "--files <files>" help="Specify files to run on"
"""
run = """
pre-commit run ${usage_hook_id} ${usage_all_files:+--all-files} ${usage_files:+--files ${usage_files}}
"""

[tasks.docs]
description = "Serve godoc at http://localhost:6060"
quiet = true
run = '''
URL="http://localhost:6060/pkg/github.com/necrom4/sbb-tui/?m=all"
echo "Open ${_LINK_START}${URL}${_LINK_SEP}${URL}${_LINK_END}"
godoc -http=:6060
'''

[[hooks.enter]]
# Verify all tools defined in [tools] are actually installed
script = """
missing=$(mise ls --missing --offline | awk '{print $1}' | tr '\n' ' ')

if [ -n "$missing" ]; then
  echo "${_C_RED}[WARNING]${_S_RESET}"
  echo "Tools defined in mise.toml are not installed: ${_C_MAGENTA}$missing${_S_RESET}"
  echo "Run '${_C_GREEN}mise install${_S_RESET}' to set up your environment."
fi
"""

[[hooks.enter]]
script = """
if [ ! -f ".git/hooks/pre-commit" ] || ! grep -q "pre-commit" ".git/hooks/pre-commit"; then
  echo "${_C_RED}[WARNING]${_S_RESET}"
  echo "Git pre-commit ${_C_MAGENTA}hooks${_S_RESET} not initialized!"
  echo "Run '${_C_GREEN}mise run init${_S_RESET}' to enable pre-commit hooks."
fi
"""
